# Generated by Django 4.1 on 2023-11-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biospecimen',
            name='file_name',
            field=models.CharField(max_length=55, verbose_name='Название файла'),
        ),
    ]
