# Generated by Django 4.1 on 2023-11-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biobank', '0002_alter_biospecimen_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='shelf',
        ),
        migrations.RemoveField(
            model_name='project',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='samplelocation',
            name='box',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='freezer',
        ),
        migrations.DeleteModel(
            name='Biospecimen',
        ),
        migrations.DeleteModel(
            name='Box',
        ),
        migrations.DeleteModel(
            name='Freezer',
        ),
        migrations.DeleteModel(
            name='Laboratory',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='SampleLocation',
        ),
        migrations.DeleteModel(
            name='Shelf',
        ),
    ]
