# Generated by Django 4.1 on 2023-11-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название лаборатории')),
                ('head_lab', models.CharField(default='', max_length=50, verbose_name='Заведующий лабораторий')),
                ('test_field', models.CharField(default='', max_length=250, verbose_name='Тестовое поле')),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатории',
            },
        ),
    ]
