# Generated by Django 4.1 on 2023-11-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('freezer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.freezer')),
            ],
        ),
        migrations.CreateModel(
            name='SampleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('count_samples', models.IntegerField(default=0)),
                ('count_rows', models.IntegerField(default=0)),
                ('count_col', models.IntegerField(default=0)),
                ('state_location', models.CharField(default='free', max_length=10)),
                ('sample_id', models.IntegerField(default=-1)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.box')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.shelf'),
        ),
    ]
